spring:
  application:
    name: Authentication-Microservice
server:
  port: 9898
rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

  datasource:
    url: jdbc:mysql://localhost:3306/userdb
    username: user
    password: secret
  jpa:
    hibernate:
      ddl-auto: update
